# When this detects changesets it will create a `Release PR`
# When it detects that pr merged it  will release packages
# for non official releases run the github action in `snapshot.yml`
# https://github.com/changesets/action#with-publishing
name: Release 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - v1

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repo
        with:
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup
        
      - name: Clean
        shell: bash
        run: pnpm turbo run clean --force --concurrency 10

      # Build without cache to ensure we release with the most accurate output
      - name: Build
        shell: bash
        run: pnpm turbo run build --force --concurrency 10

      - name: Outdated files, run `pnpm build` and commit them
        uses: ./.github/actions/require-empty-diff

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      # https://github.com/changesets/action#with-publishing
      - name: Handle Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: Version packages 🔖"
          commit: "chore: Version packages 🔖"
          publish: pnpm release
          version: pnpm release:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

